services:
  streamlit:
    #build: .
    image: registry.gitlab.com/kondziuu03/rag-llm
    ports:
      - "8501:8501"
    volumes:
      - data:/app/data
      - chroma:/app/chroma
      - ~/.cache/huggingface:/root/.cache/huggingface
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
  ollama:
    container_name: ollama-service
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
volumes:
  ollama:
  data:
  chroma:
  hugs_cache: