services:
  streamlit:
    # build: .
    image: registry.gitlab.com/kondziuu03/rag-llm
    ports:
      - "8501:8501"
    volumes:
      - data:/app/data
      - chroma:/app/chroma
      - ~/.cache/huggingface:/root/.cache/huggingface
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
  data:
  chroma:
  hugs_cache: